name = "aoc"
version = "0.1.0"
license = "license"
author = "Owen Jones"
maintainer = "owen@owenjones.net"
copyright = "Copyright 2025, Owen Jones"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[dependencies]
stdlib = "*"
M_strings = { git = "https://github.com/urbanjost/M_strings.git" }
forgex = { git = "https://github.com/shinobuamasaki/forgex" }

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
